### ISSUE TITLE
App crashes after selecting file and trying to flash P8-b watch

### ISSUE THREAD

**Issue by annoyinganime** [atc1441/DaFlasherFiles#18]
App crashes when I select file for flashing ([DaFitBootloader23Hacked.bin](https://github.com/atc1441/DaFlasherFiles/blob/master/DaFitBootloader23Hacked.bin))
Here's an error that android gives me:
```
type: crash
osVersion: google/sunfish/sunfish:13/
package: com.atcnetz.paatc.patc:61
process: com.atcnetz.paatc.patc
processUptime: 34940 + 324 ms

java.lang.StringIndexOutOfBoundsException: begin 0, end 10, length 0
 at java.lang.String.checkBoundsBeginEnd(String.java:3942)
 at java.lang.String.substring(String.java:2467)
 at com.atcnetz.patc.daatc.DeviceActivity$4.run(DeviceActivity.java:568)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7903)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ExecInit.main(ExecInit.java:49)
 at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
 at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)
```

**Comment by annoyinganime** [comment]
Nevermind, new P8 watches come not with NRF52 chips bun something else chinese, so seems like they're basically incompatible. 
Also, please add in Readme that only older P8 watches are compatible!
